version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: emily-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_banco_local_123
      POSTGRES_DB: emily_atele
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: emily-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
